# Generated by Django 4.2.1 on 2023-05-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('complexity_rating', models.FloatField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('frequency_rating', models.IntegerField()),
                ('pos', models.CharField(max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='WordInSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
            options={
                'indexes': [models.Index(fields=['word', 'sentence'], name='languages_w_word_id_a7cfd4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='languages_w_word_424db4_idx'),
        ),
    ]
