# Generated by Django 5.0 on 2024-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='frequency_rating',
        ),
        migrations.RemoveField(
            model_name='word',
            name='pos',
        ),
    ]
