# Generated by Django 4.2.1 on 2023-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(to='languages.word'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='type',
            field=models.ManyToManyField(to='languages.sentencetype'),
        ),
    ]
