# Generated by Django 4.2.1 on 2023-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_sentence_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
