# Generated by Django 4.2.3 on 2023-10-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_sentence_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='sentence_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='complexity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='theme',
            field=models.CharField(blank=True, default='general', max_length=100),
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='translation',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='type',
            field=models.ManyToManyField(blank=True, to='languages.sentencetype'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(blank=True, to='languages.word'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translation',
            field=models.ManyToManyField(blank=True, null=True, related_name='translated_sentences', to='languages.sentence'),
        ),
    ]
