# Generated by Django 4.2.3 on 2023-10-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_auto_20231017_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
