# Generated by Django 4.2.3 on 2023-10-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_sentence_sentence_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_sources', to='languages.language')),
                ('source_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_from', to='languages.sentence')),
                ('translated_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_languages', to='languages.language')),
                ('translated_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_to', to='languages.sentence')),
            ],
            options={
                'unique_together': {('source_sentence', 'translated_sentence')},
            },
        ),
    ]
