# Generated by Django 5.0 on 2023-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_alter_sentence_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='category',
            field=models.CharField(choices=[('L', 'Learning'), ('N', 'Native'), ('B', 'Both')], default='B', max_length=1),
        ),
    ]
