# Generated by Django 5.0 on 2024-05-25 09:54

import django.db.models.deletion
import user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField(default=0.0)),
                ('proficiency_weights', models.JSONField(default=user_management.models.default_weights)),
                ('is_active', models.BooleanField(default=False)),
                ('buffer_size', models.FloatField(default=0.1)),
                ('buffer_location', models.FloatField(default=0.0)),
                ('buffer_range_start', models.IntegerField(default=0)),
                ('buffer_range_end', models.IntegerField(default=500)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_languages', models.ManyToManyField(related_name='learning_users', through='user_management.UserLearningLanguage', to='languages.language')),
                ('native_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_language', to='languages.language')),
                ('subscribed_decks', models.ManyToManyField(blank=True, through='learning.UserDeckSubscription', to='learning.deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlearninglanguage',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_manage_user_id_016aba_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearninglanguage',
            index=models.Index(fields=['user_profile', 'language', 'is_active'], name='user_manage_user_pr_c1ee0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlearninglanguage',
            unique_together={('user_profile', 'language')},
        ),
    ]
