# Generated by Django 5.0 on 2024-05-04 05:24

import django.db.models.deletion
import user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField(default=0.0)),
                ('proficiency_weights', models.JSONField(default=user_management.models.default_weights)),
                ('is_active', models.BooleanField(default=False)),
                ('buffer_size', models.FloatField(default=0.1)),
                ('buffer_location', models.FloatField(default=0.0)),
                ('buffer_range_start', models.IntegerField(default=0)),
                ('buffer_range_end', models.IntegerField(default=500)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_languages', models.ManyToManyField(related_name='learning_users', through='user_management.UserLanguageProficiency', to='languages.language')),
                ('native_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_language', to='languages.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userlanguageproficiency',
            unique_together={('user_profile', 'language')},
        ),
    ]
