# Generated by Django 4.2.1 on 2023-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userprofile_learning_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buffer_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='buffer_size',
        ),
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='buffer_location',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='buffer_size',
            field=models.FloatField(default=0.0),
        ),
    ]
