# Generated by Django 4.2.1 on 2023-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_userlanguageproficiency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='buffer_range_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='buffer_range_start',
            field=models.IntegerField(default=0),
        ),
    ]
