# Generated by Django 4.2.1 on 2023-05-31 12:46

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userlanguageproficiency_buffer_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguageproficiency',
            name='proficiency_weights',
            field=models.JSONField(default=user_management.models.default_weights),
        ),
    ]
