# Generated by Django 4.2.3 on 2023-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_userlanguageproficiency_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguageproficiency',
            name='buffer_range_end',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='userlanguageproficiency',
            name='buffer_size',
            field=models.FloatField(default=0.1),
        ),
    ]
