# Generated by Django 5.0 on 2023-12-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_rename_is_active_userprofile_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activated',
        ),
    ]
