# Generated by Django 5.0 on 2024-05-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'Binary'), ('B', 'Similarity')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'date'], name='scoring_sco_user_pr_69b759_idx')],
            },
        ),
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
                ('word_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userwordbank')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'word_item', 'date'], name='scoring_wor_user_pr_b82bfd_idx')],
            },
        ),
    ]
