# Generated by Django 4.2.1 on 2023-05-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'word', 'date'], name='scoring_wor_user_pr_712518_idx')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'date'], name='scoring_sco_user_pr_69b759_idx')],
            },
        ),
    ]
