# Generated by Django 4.2.3 on 2023-08-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_learning_us_user_pr_6593cc_idx_learning_us_user_pr_a736fc_idx_and_more'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordscore',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userword'),
        ),
    ]
