# Generated by Django 4.2.3 on 2023-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_wordscore_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'Binary'), ('B', 'Similarity')], default='B', max_length=1)),
            ],
        ),
    ]
