# Generated by Django 4.2.1 on 2023-05-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField()),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'word'], name='learning_us_user_pr_6593cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField()),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.sentence')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'sentence'], name='learning_us_user_pr_5ce176_idx')],
            },
        ),
    ]
