# Generated by Django 5.0 on 2024-04-29 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyWordDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_rating', models.IntegerField()),
                ('word_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('custom', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_word', models.CharField(max_length=100)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPracticeBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer', models.JSONField(default=dict)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile'], name='learning_us_user_pr_1f3d14_idx')],
                'unique_together': {('user_profile', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField()),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.sentence')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'sentence'], name='learning_us_user_pr_5ce176_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.FloatField()),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
                ('word_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'word_item'], name='learning_us_user_pr_9a0e69_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWordDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
                ('word_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile'], name='learning_us_user_pr_0dcec0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userworddeck',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0.0), ('priority__lte', 1.0)), name='UserWordDeck_priority_range'),
        ),
        migrations.AddIndex(
            model_name='userworddeposit',
            index=models.Index(fields=['user_profile', 'user_word', 'weight', 'date_of_entry'], name='learning_us_user_pr_c0f668_idx'),
        ),
        migrations.AddConstraint(
            model_name='userworddeposit',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0.0), ('weight__lte', 1.0)), name='UserWordDeposit_weight_range'),
        ),
    ]
