# Generated by Django 5.0 on 2024-05-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckvisibility',
            name='value',
            field=models.IntegerField(choices=[('private', 'Private'), ('public', 'Public')], unique=True),
        ),
    ]
