# Generated by Django 4.2.1 on 2023-06-19 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_sentence_translation'),
        ('user_management', '0007_alter_userlanguageproficiency_proficiency_level'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPracticeBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer', models.JSONField(default=dict)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile'], name='learning_us_user_pr_1f3d14_idx')],
                'unique_together': {('user_profile', 'language')},
            },
        ),
    ]
