# Generated by Django 4.2.1 on 2023-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userpracticebuffer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userword',
            new_name='learning_us_user_pr_a736fc_idx',
            old_name='learning_us_user_pr_6593cc_idx',
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
