# Generated by Django 5.0 on 2024-04-29 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0002_userwordbank_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencyworddeck',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
