# Generated by Django 5.0 on 2024-05-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_deck_rank_type_alter_deckword_rank'),
        ('user_management', '0002_alter_userlearninglanguage_proficiency_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdecksubscription',
            unique_together={('user_profile', 'deck')},
        ),
    ]
