# Generated by Django 5.0 on 2024-04-14 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_learning_us_user_pr_6593cc_idx_learning_us_user_pr_a736fc_idx_and_more'),
        ('scoring', '0003_comparisonmode'),
        ('user_management', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_word', models.CharField(max_length=100)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.RenameModel(
            old_name='UserWord',
            new_name='UserWordBank',
        ),
        migrations.RemoveIndex(
            model_name='userwordbank',
            name='learning_us_user_pr_a736fc_idx',
        ),
        migrations.RenameField(
            model_name='userwordbank',
            old_name='word',
            new_name='wordItem',
        ),
        migrations.AddIndex(
            model_name='userwordbank',
            index=models.Index(fields=['user_profile', 'wordItem'], name='learning_us_user_pr_5a1217_idx'),
        ),
        migrations.AddField(
            model_name='userworddeposit',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile'),
        ),
        migrations.AddIndex(
            model_name='userworddeposit',
            index=models.Index(fields=['user_profile', 'user_word', 'weight', 'date_of_entry'], name='learning_us_user_pr_c0f668_idx'),
        ),
        migrations.AddConstraint(
            model_name='userworddeposit',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0.0), ('weight__lte', 1.0)), name='UserWordDeposit_weight_range'),
        ),
    ]
