# Generated by Django 5.0 on 2024-05-01 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0003_frequencyworddeck_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworddeck',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userworddeck',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
