# Generated by Django 5.0 on 2024-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_deck_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='visibility',
            field=models.ForeignKey(on_delete=models.SET('public'), to='learning.deckvisibility'),
        ),
    ]
