# Generated by Django 5.0 on 2024-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_userdecksubscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_ranked',
            field=models.BooleanField(default=True),
        ),
    ]
