# Generated by Django 5.0 on 2024-04-20 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '0013_language_category'),
        ('learning', '0004_userworddeposit_rename_userword_userwordbank_and_more'),
        ('user_management', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('custom', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('priority', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile'], name='learning_us_user_pr_0dcec0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userworddeck',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0.0), ('priority__lte', 1.0)), name='UserWordDeck_priority_range'),
        ),
    ]
