# Generated by Django 5.0 on 2024-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_userworddeck_active_userworddeck_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworddeck',
            old_name='priority',
            new_name='priority_rating',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='custom',
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='fail_pass_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='proficiency',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='times_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='times_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
    ]
