# Generated by Django 5.0 on 2024-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '0001_initial'),
        ('learning', '0005_alter_deck_visibility'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userwordbuffer',
            name='learning_us_user_pr_42d15b_idx',
        ),
        migrations.RenameField(
            model_name='userwordbuffer',
            old_name='deck_type',
            new_name='deck_source',
        ),
        migrations.AddIndex(
            model_name='userwordbuffer',
            index=models.Index(fields=['user_profile', 'deck_source', 'object_id'], name='learning_us_user_pr_dae58f_idx'),
        ),
    ]
