# Generated by Django 5.0 on 2024-04-20 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_language_category'),
        ('learning', '0005_userwordbuffer_userworddeck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyWordDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_rating', models.IntegerField()),
                ('word_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
        ),
    ]
