# Generated by Django 5.0 on 2024-05-01 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_remove_word_frequency_rating_remove_word_pos'),
        ('learning', '0006_remove_userworddeck_userworddeck_priority_range_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userworddeck',
            name='UserWordDeck_priority_rating_range',
        ),
        migrations.AlterField(
            model_name='userwordbuffer',
            name='fail_pass_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='userwordbuffer',
            name='priority',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userwordbuffer',
            name='proficiency',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userworddeck',
            name='priority_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddConstraint(
            model_name='userworddeck',
            constraint=models.CheckConstraint(check=models.Q(('priority_rating__gte', 0.0), ('priority_rating__lte', 1.0)), name='UserWordDeck_priority_rating_range'),
        ),
    ]
