# Generated by Django 5.0 on 2024-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_deck_rank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckword',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
    ]
