# Generated by Django 5.0 on 2024-05-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_userwordbuffer_learning_us_user_pr_42d15b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemdeck',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='systemdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.deck'),
        ),
        migrations.AlterField(
            model_name='userdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to='learning.deck'),
        ),
    ]
