# Generated by Django 5.0 on 2024-05-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_systemdeck_options_alter_systemdeck_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_decks', to='learning.deck'),
        ),
    ]
