# Generated by Django 5.0 on 2024-05-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0007_alter_deckword_rank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckword',
            unique_together={('deck', 'word_item')},
        ),
    ]
