# Generated by Django 5.0 on 2024-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('languages', '0002_remove_word_frequency_rating_remove_word_pos'),
        ('learning', '0007_remove_userworddeck_userworddeck_priority_rating_range_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userwordbuffer',
            index=models.Index(fields=['user_profile', 'content_type', 'object_id'], name='learning_us_user_pr_3724be_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordbuffer',
            index=models.Index(fields=['user_profile', 'priority'], name='learning_us_user_pr_fabb82_idx'),
        ),
        migrations.AddConstraint(
            model_name='userwordbuffer',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0.0), ('priority__lte', 1.0)), name='UserWordBuffer_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='userwordbuffer',
            constraint=models.CheckConstraint(check=models.Q(('proficiency__gte', 0.0), ('proficiency__lte', 1.0)), name='UserWordBuffer_proficiency_range'),
        ),
    ]
