# Generated by Django 5.0 on 2024-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0008_alter_systemdeck_deck'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdeck',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveIndex(
            model_name='deck',
            name='learning_de_name_e6a582_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemdeck',
            name='learning_sy_deck_id_83a5dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdeck',
            name='learning_us_user_pr_0f975d_idx',
        ),
        migrations.AlterField(
            model_name='deck',
            name='visibility',
            field=models.ForeignKey(on_delete=models.SET('private'), to='learning.deckvisibility'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['name', 'language'], name='learning_de_name_855535_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdeck',
            index=models.Index(fields=['deck', 'word_item', 'rank'], name='learning_sy_deck_id_fa15b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeck',
            index=models.Index(fields=['user_profile', 'rank', 'word_item'], name='learning_us_user_pr_b537e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdeck',
            constraint=models.UniqueConstraint(fields=('deck', 'word_item'), name='unique_userdeck'),
        ),
    ]
