# Generated by Django 5.0 on 2024-05-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_userdecksubscription_learning_us_user_pr_81e2e3_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='language',
        ),
    ]
