# Generated by Django 5.0 on 2024-05-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learning', '0010_remove_userwordbuffer_language'),
        ('user_management', '0002_alter_userlearninglanguage_proficiency_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeckBufferWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.DecimalField(decimal_places=2, max_digits=3)),
                ('proficiency', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('fail_pass_ratio', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_passed', models.IntegerField(default=0)),
                ('times_failed', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='userwordbuffer',
            name='UserWordBuffer_proficiency_range',
        ),
        migrations.RemoveIndex(
            model_name='userwordbuffer',
            name='learning_us_user_pr_446ce2_idx',
        ),
        migrations.RemoveIndex(
            model_name='userwordbuffer',
            name='learning_us_user_pr_fabb82_idx',
        ),
        migrations.RenameField(
            model_name='userwordbuffer',
            old_name='deck_source',
            new_name='deck',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='fail_pass_ratio',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='times_failed',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='times_passed',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='times_seen',
        ),
        migrations.RemoveField(
            model_name='userwordbuffer',
            name='word_item',
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='deck_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordbuffer',
            name='is_fully_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='userwordbuffer',
            index=models.Index(fields=['user_profile', 'deck'], name='learning_us_user_pr_1de859_idx'),
        ),
        migrations.AddField(
            model_name='userdeckbufferword',
            name='word_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word'),
        ),
        migrations.AddConstraint(
            model_name='userdeckbufferword',
            constraint=models.CheckConstraint(check=models.Q(('proficiency__gte', 0.0), ('proficiency__lte', 1.0)), name='UserWordBuffer_proficiency_range'),
        ),
    ]
