# Generated by Django 5.0 on 2024-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_userdeckbufferword_buffer_userwordbuffer_word_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeckbufferword',
            name='fail_pass_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
