# Generated by Django 5.0 on 2024-05-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_userdeckbufferword_fail_pass_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deckword',
            options={'ordering': ['rank']},
        ),
    ]
